### ISSUE TITLE
transfer scraper exception

### ISSUE THREAD

**Issue by johnnyapol** [quacs/quacs#459]
```
Traceback (most recent call last):
  File "/home/runner/work/quacs/quacs/scrapers/transfer_scraper/main.py", line 210, in <module>
    school_ids = asyncio.run(get_school_ids())
Getting list of schools
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/runner/work/quacs/quacs/scrapers/transfer_scraper/main.py", line 68, in get_school_ids
    school_ids += await asyncio.gather(
  File "/home/runner/work/quacs/quacs/scrapers/transfer_scraper/main.py", line 46, in get_specific_school_ids
    ids = get_ids(homepage, "sbgi_code")
  File "/home/runner/work/quacs/quacs/scrapers/transfer_scraper/main.py", line 22, in get_ids
    assert len(selectbox_html) == 1
AssertionError
Error: Process completed with exit code 1.
```

Observed on latest run: https://github.com/quacs/quacs/runs/2375965781

**Comment by johnnyapol** [comment]
Closing this out as an RPI backend issue, since it failed so many times I thought it was an actual issue on our code. Latest run has it passing w/o any changes: https://github.com/quacs/quacs/runs/2376365815

**Comment by benjaminrsherman** [comment]
There weren't any changes to the scraped pages?
